version: '3'
services:
  app:
    build: .
    tty: true
    platform: linux/amd64
    ports:
      - 9090:9090
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nn_chat
      TZ: "Asia/Tokyo"
    volumes:
      - ../nn-chat-db:/var/lib/postgresql/data